In [36]:
from numpy.linalg import inv
import numpy as np
  
a = np.array([[3,  2,  -1],
             [2,  -2,  4],
             [-1,  0.5,  -1]])
                
ainv = inv(np.matrix(a))
ainv           
b= np.array([1,-2,0])

c= np.linalg.solve(a,b)

print(ainv)
print(b)
print(c)


[[ 1.48029737e-16 -5.00000000e-01 -2.00000000e+00]
 [ 6.66666667e-01  1.33333333e+00  4.66666667e+00]
 [ 3.33333333e-01  1.16666667e+00  3.33333333e+00]]
[ 1 -2  0]
[ 1. -2. -2.]
